server.port=8019
management.server.port=8019

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://mongo:27017
spring.data.mongodb.database=FSE_GTW

transactions.mongodb.uri=mongodb://mongo-db:27017
valdoc.mongodb.uri=mongodb://mongo-db:27017
rules.mongodb.uri=mongodb://mongo-db:27017

#######################################
#			DATA RETENTION RULES
#######################################
retention.transactions-query.limit=500

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console

#######################################
# Microservices url
#######################################
ms.url.gtw-config=http://it-fse-gtw-config:8018

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none

otel.propagators=tracecontext,baggage